name: "Deploy CodigoFacilito"

on: 
  push:
    branches: ["master"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hacemos pull del código"
          echo "Correr migraciones"
          echo "Generar binario"
          echo "Publicar Versión"